spring:
  application.name: onion-presentation
  docker.compose:
    lifecycle-management: start_only
    skip.in-tests: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
  sql.init.mode: always

logging:
  include-application-name: false
  pattern:
    dateformat: HH:mm:ss.SSS
  level:
    org.postgresql.Driver: debug
    #org.springframework.jdbc.core.JdbcTemplate: debug
